### PR TITLE
Defaults to include all packages in source directories

### PR DESCRIPTION
**Pull request by jbristow**
Ok, here's my first pass. I haven't checked it with complicated `:source-paths` variables yet, and I think I might have fixed a bug where nothing was being included unless it matched everything?

This is for issue #1, and *please* be brutal as I just kicked this out in a few hours and my macros are a little rusty.

### CODE REVIEW

**Comment by camsaul** [comment]
Super sorry @jbristow, I just saw this PR right now, I must have missed the email

I'll take a look at it first thing tomorrow

**Comment by jbristow** [comment]
Friendly ping! 🛎  (We're all busy, and I literally hadn't thought of this PR until I was messing with my vimrc this morning.)

**Comment by camsaul** [comment]
Sorry for the delay @jbristow. Looks good!

**Comment by camsaul** [comment]
Just pushed new release 1.0.1 that includes the fix. Thanks!

**Comment by jbristow** [comment]
:sunglasses: Glad to help!

**Pull request merged**
